resources:
  Resources:
    surveys:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Surveys
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: EntityType
            AttributeType: S
          - AttributeName: Target
            AttributeType: S
          - AttributeName: FinalDate
            AttributeType: S
        GlobalSecondaryIndexes:
          - IndexName: SurveyType
            KeySchema:
              - AttributeName: EntityType
                KeyType: HASH
              - AttributeName: SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: SurveyTarget
            KeySchema:
              - AttributeName: Target
                KeyType: HASH
              - AttributeName: FinalDate
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST